// nằm ở /etc/nginx/sites-available/waf.conf
log_format waf '$remote_addr [$time_local] '
               '"$request" $status '
               'ua="$http_user_agent" '
               'xff="$http_x_forwarded_for" '
               'rt=$request_time';

limit_req_zone $binary_remote_addr zone=ratelimit:10m rate=10r/s;

server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/waf_access.log waf;

    location / {

        # Rate limit
        limit_req zone=ratelimit burst=20 nodelay;

        # Block simple bots (demo)
        if ($http_user_agent ~* "(curl|wget|python)") {
            return 403;
        }

        proxy_pass http://192.168.1.112:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
